Refactor std::string to std::vector/array/span for storing bytes
SparqNet/orbitersdk-cpp pull request #45
Opened 2023-06-13 00:43 UTC by itamarcps

This is a major update where we have comprehensively overhauled the way we handle raw byte storage in the codebase. We have shifted from using std::string and std::string_view to std::vector<uint8_t>, std::array<uint8_t> and std::span<uint8_t>. This change is motivated by a desire to enhance clarity, efficiency, and robustness in handling raw bytes, especially in the context of TCP sockets which operate on uint8_t arrays.

Our new byte storage and viewing approach employs the following:

```cpp
using Byte = uint8_t;
using Bytes = std::vector<Byte>;
template <std::size_t N>
using BytesArr = std::array<Byte, N>;
using BytesArrView = std::span<const Byte, std::dynamic_extent>;
using BytesArrMutableView = std::span<Byte, std::dynamic_extent>;
```

The breadth of the modification impacts almost every aspect of our code. Alongside the primary change, we've also introduced several enhancements and adjustments to provide better context, such as duplicating some ABI functions to accommodate both Bytes and std::string, refactoring FixedString to FixedArr and opting for std::array instead (take note that std::array cannot leverage std::move as uint8_t is not movable), and incorporating new utility functions. Numerous functions now also take std::span as an argument. I would kindly ask reviewers to pay special attention to the utils.h and strings.h classes.

The most critical alteration concerns ethCallInfo, which now includes an additional Functor variable in its tuple. Moreover, the data attribute of ethCallInfo now returns a BytesArrView, necessitating careful consideration of data ownership. The ethCallInfo structure is now as follows:

```
/// ethCallInfo: tuple of (from, to, gasLimit, gasPrice, value, functor, data)
/// **ATTENTION**: Be aware that we are using BytesArrView, so you MUST be sure that the data allocated in the BytesArrView is valid during the whole life of the tuple.
/// If you need ethCallInfo to own the data, use ethCallInfoAllocated instead.
using ethCallInfo = std::tuple<Address,Address,uint256_t, uint256_t, uint256_t, Functor, BytesArrView>;
/// This is the same as ethCallInfo, but using Bytes instead of BytesArrView, truly allocating the data, some places need it such as tests.
using ethCallInfoAllocated = std::tuple<Address,Address,uint256_t, uint256_t, uint256_t, Functor, Bytes>;
```

When using std::span, it's essential to remember that it does not own the data. This means that you need to ensure the integrity of the array that std::span is referencing for the span's duration, ethCallInfoAllocated is used when needed (such as tests). To append the return of a function to bytes, it's recommended to use Utils::appendBytes.

Given the extent of the changes, we acknowledge the possibility of conflicts, and I take full responsibility for their resolution. Your detailed review and feedback on this extensive refactor will be highly appreciated.

2023-06-13 16:07 UTC, jcarraror commented
There's a lot of magic numbers in abi.h (for offsets and byte skipping). I get the context and it's clear for me, but it's not better to have this values in a proper named variable? This way we avoid any kind of confusion in interpreting that values.

2023-06-13 20:11 UTC, itamarcps commented
> There's a lot of magic numbers in the project(for offsets and byte skipping). I get the context and it's clear for me, but it's not better to have this values in a proper named variable? This way we avoid any kind of confusion in interpreting that values.


Some might be able to be added as global const, It could be used on Block. others are "dynamic" that depends on the size of the previous, what is your suggestion?

2023-06-13 20:41 UTC, jcarraror commented
> > There's a lot of magic numbers in the project(for offsets and byte skipping). I get the context and it's clear for me, but it's not better to have this values in a proper named variable? This way we avoid any kind of confusion in interpreting that values.
> 
> Some might be able to be added as global const, It could be used on Block. others are "dynamic" that depends on the size of the previous, what is your suggestion?

A good way is to define a header for this constants (probably in the utils folder)

2023-06-14 17:15 UTC, jcarraror requested changes

2023-06-14 19:18 UTC, Jean-Lessa requested changes
Finished reviewing, left a lot of small suggestions (most of them to do with either Doxygen or indentation/code formatting).

2023-06-14 19:18 UTC, Jean-Lessa commented on tests/contract/erc20wrapper.cpp
>  /// Forward Decleration.
```suggestion
// Forward declaration.
```

2023-06-14 19:18 UTC, Jean-Lessa commented on tests/contract/nativewrapper.cpp
>  /// Forward Decleration.
```suggestion
// Forward declaration.
```

2023-06-14 19:18 UTC, Jean-Lessa commented on src/contract/variables/safeunorderedmap.h
> +  ///< Check if pointers are initialized (and initialize them if not).
```suggestion
  /// Check if pointers are initialized (and initialize them if not).
```

2023-06-14 19:18 UTC, Jean-Lessa commented on src/contract/variables/safeunorderedmap.h
> +  ///< Copy constructor.
```suggestion
  /// Copy constructor.
```

2023-06-14 19:18 UTC, Jean-Lessa commented on src/contract/variables/safeunorderedmap.h
> +  ///< Revert the value. Nullifies the pointers and unregisters the variable.
```suggestion
  /// Revert the value. Nullifies the pointers and unregisters the variable.
```

2023-06-14 19:18 UTC, Jean-Lessa commented on src/contract/contractmanager.cpp
> +  this->contracts.insert(std::make_pair(derivedContractAddress, std::make_unique<ERC20>(decoder.getData<std::string>(0),
Indentation could be fixed here.

2023-06-14 19:19 UTC, Jean-Lessa requested changes
Finished reviewing, left a lot of small suggestions (most of them to do with either Doxygen or indentation/code formatting).

2023-06-15 17:11 UTC, jcarraror approved these changes

2023-06-15 18:05 UTC, itamarcps commented on src/utils/db.h
> +  const Bytes blocks = { 0x00, 0x01 };
Yes, duplicated during the merge, removed.

2023-06-15 18:54 UTC, Jean-Lessa commented on src/utils/utils.h
> + * ...
I think I specified this poorly now that I realize it, the `...` was meant to be "the rest of the comment lines below it". My bad, just fixed it myself with 998c843.

2023-06-15 18:54 UTC, Jean-Lessa approved these changes
All good! Approving it :ok_hand:

2023-06-15 18:57 UTC, merged