Development 0.1.2
SparqNet/orbitersdk-cpp pull request #66
Opened 2023-07-28 17:16 UTC by itamarcps

This pull request proposes significant updates for the upcoming 0.1.2 release of OrbiterSDK. It includes two main enhancements to improve performance and versatility of the system:

- New Logger Class: Introduced a robust and efficient logger class, aimed at resolving the issue of prolonged mutex wait times associated with I/O operations in multithreaded environments. This logger utilizes a queue-based system to manage log data, reducing the number of I/O operations and improving overall system performance.

- Enhanced Contract Function Arguments: Expanded the types of arguments allowed in contract functions. Previously, all arguments were required to be uint256. This update introduces the support for all uint types (such as uint8, uint16, uint32, etc), offering greater flexibility when defining contract functions.

2023-07-28 18:05 UTC, Jean-Lessa requested changes
Logger seems to be good. I'm assuming those extra DEX contracts are working as intended. Left a few thoughts.

2023-07-28 18:05 UTC, Jean-Lessa commented on src/net/p2p/encoding.cpp
> -    Utils::logToDebug(Log::P2PRequestDecoder, __func__, std::string("Data size: ") + std::to_string(data.size()) + " data: " + Hex::fromBytes(data).get());
Suppose this was meant to be converted to a `Logger::logToDebug()` call instead of just being deleted? If not please ignore.

2023-07-28 18:05 UTC, Jean-Lessa commented on src/utils/hex.cpp
> +  if (retHex == "0x") { return retHex; };
Isn't RPC supposed to be "0x0" here as per Ethereum standards (check the header comment on this function)? If yes please fix, if not please ignore.

2023-07-30 12:18 UTC, jcarraror requested changes

2023-07-30 12:22 UTC, jcarraror requested changes
Aside my points, tests are failing in HTTPJsonRPC, ContractABIGenerator and Hex test cases. More details can be seen in the pipeline output.

2023-07-31 18:08 UTC, itamarcps commented
Pull request closed due to development being "infected" with files from dex-demo, another PR will be created with a new development branch with the proper commit to be PR'ed to main.

2023-07-31 18:08 UTC, closed without merging